version: "3.7"


volumes:
   nwp_data:
   sat_data:

services:
  postgres-forecast:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  postgres-pv:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"


  # database migrations
  datamodel:
    image: openclimatefix/nowcasting_datamodel
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - DB_URL_PV=postgresql://postgres:postgres@postgres-pv:5432/postgres
    depends_on:
      - "postgres-pv"
      - "postgres-forecast"

  nwp:
    image: openclimatefix/metoffice_weather_datahub
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
      - SAVE_DIR=data
      - API_KEY=$NWP_API_KEY
      - API_SECRET=$NWP_API_SECRET
    volumes:
      - type: volume
        source: nwp_data
        target: /app/data

  sat:
    image: openclimatefix/satip
    environment:
      - LOG_LEVEL=DEBUG
      - SAVE_DIR=sat_data
      - API_KEY=$SAT_API_KEY
      - API_SECRET=$SAT_API_SECRET
    volumes:
      - type: volume
        source: sat_data
        target: /app/data

  pv:
    image: openclimatefix/pvconsumer
    environment:
      - DB_URL_FORECAST=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - DB_URL=postgresql://postgres:postgres@postgres-pv:5432/postgres
      - LOGLEVEL=DEBUG
      - API_KEY=$PVOUTPUT_API_KEY
      - SYSTEM_ID=$PVOUTPUT_SYSTEM_ID
      - DATA_SERVICE_URL=https://pvoutput.org/
      - FILENAME=./pvconsumer/data/pv_systems_10.csv
    depends_on:
      - "postgres-pv"
    restart: on-failure

  gsp:
    image: openclimatefix/gspconsumer
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - LOGLEVEL=DEBUG
      - N_GSPS=339 # 338 + 1 national
    depends_on:
      - "postgres-forecast"
    restart: on-failure


  forecast:
    image: openclimatefix/nowcasting_forecast
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
      - NWP_PATH=./data/latest.netcdf
      - MODEL_NAME=nwp_simple_trained
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    depends_on:
      - "postgres-forecast"
    restart: on-failure
    volumes:
      - type: volume
        source: nwp_data
        target: /app/data


  api:
    image: openclimatefix/nowcasting_api
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
    depends_on:
      - "postgres-forecast"
      - "postgres-pv"
      - "forecast"
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80" ]
    ports:
      - 80:80
