name: Local Stack tests
# This work flow runs 'terraform validate' to check there isn't anything obviously wrong

on: [push]

jobs:
  tests:
    name: Local Stack Tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run
      run: |
        cd local-stack/
        pip install -r tests/requirements.txt

        # start up the stack
        docker-compose up -d

        # wait 2 minutes
        echo "Sleeping for 10 minutes, to let the local stackrun"
        sleep 600

        # run tests
        pytest

        # pull down stack
        docker-compose down
      env: #
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NWP_API_KEY: ${{ secrets.NWP_API_KEY }}
        NWP_API_SECRET: ${{ secrets.NWP_API_SECRET }}
        PVOUTPUT_API_KEY: ${{ secrets.PVOUTPUT_API_KEY }}
        PVOUTPUT_SYSTEM_ID: ${{ secrets.PVOUTPUT_SYSTEM_ID }}
        SAT_API_KEY: ${{ secrets.SAT_API_KEY }}
        SAT_API_SECRET: ${{ secrets.SAT_API_SECRET }}
